name: nameko-sentry CI build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Upgrade pip
        run: pip install pip setuptools wheel --upgrade
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Run tox
        run: python -m tox

